### PR TITLE
Modify the code, compatible with java8, please use java compile push …

### PR DESCRIPTION
**Pull request by litongjava**
Modify the code, compatible with java8, please use java compile push package maven center

### CODE REVIEW

**Comment by litongjava** [comment]
please review code

**Comment by GiviMAD** [comment]
Hello, I don't want to use java 8 in the project.

I've created a Java 8 branch, if you want to reopen your PR against that branch I can merge the changes and deploy with the CI.

BR

**Comment by zjarlin** [comment]
现在中央仓库有支持8的包嘛?

**Comment by zjarlin** [comment]
> 现在中央仓库有支持8的包嘛?

implementation("site.addzero:whisper-jni:0.0.642")
     <dependency>
        <groupId>site.addzero</groupId>
        <artifactId>whisper-jni</artifactId>
        <version>0.0.642</version>
    </dependency>

**Pull request closed without merging**
